name: forcechat
description: A sample chat application with Force
dependencies:
  logging: '>=0.9.0 <0.10.0'
  force: ">=0.5.7 <0.6.0"
  http: '>=0.9.0 <0.10.0'
  http_server: '>=0.9.0 <0.10.0'
  logging: '>=0.9.0 <0.10.0'

